// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFcGIxTFs1fiUKV3PmUzQBu8wTJf_kn5Q',
    appId: '1:409071309105:web:c006a869591cfd9a106010',
    messagingSenderId: '409071309105',
    projectId: 'creatorproof-91728',
    authDomain: 'creatorproof-91728.firebaseapp.com',
    storageBucket: 'creatorproof-91728.firebasestorage.app',
    measurementId: 'G-SPY8J8FSQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5-snH2xoVNb_Eyf3cDtK9-VeDLUwK0ys',
    appId: '1:409071309105:android:875ce34b35b40f01106010',
    messagingSenderId: '409071309105',
    projectId: 'creatorproof-91728',
    storageBucket: 'creatorproof-91728.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAga8TkR4434mYoFzKMpBFpz9bzL3xV43I',
    appId: '1:409071309105:ios:1a7aa827fe02f486106010',
    messagingSenderId: '409071309105',
    projectId: 'creatorproof-91728',
    storageBucket: 'creatorproof-91728.firebasestorage.app',
    iosClientId:
        '409071309105-cccqolvnmboq3oo17t9e435c5spnk2nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.creatorProof',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAga8TkR4434mYoFzKMpBFpz9bzL3xV43I',
    appId: '1:409071309105:ios:1a7aa827fe02f486106010',
    messagingSenderId: '409071309105',
    projectId: 'creatorproof-91728',
    storageBucket: 'creatorproof-91728.firebasestorage.app',
    iosClientId:
        '409071309105-cccqolvnmboq3oo17t9e435c5spnk2nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.creatorProof',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFcGIxTFs1fiUKV3PmUzQBu8wTJf_kn5Q',
    appId: '1:409071309105:web:5ed1c92fa92935ec106010',
    messagingSenderId: '409071309105',
    projectId: 'creatorproof-91728',
    authDomain: 'creatorproof-91728.firebaseapp.com',
    storageBucket: 'creatorproof-91728.firebasestorage.app',
    measurementId: 'G-JY8RX5HVTT',
  );
}
